name: mymushaf
description: "Mushaf"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.9
  sqflite: ^2.4.2+1
  provider: ^6.1.5+1
  path: ^1.9.1
  salomon_bottom_bar: ^3.3.2
  hive_ce: ^2.19.3
  path_provider: ^2.1.5
  wakelock_plus: ^1.6.0
  flutter_material_color_picker: ^1.2.0
  scrollable_positioned_list: ^0.3.8
  share_plus: ^13.1.0
  pasteboard: ^0.5.0
  arabic_justified_text: ^1.0.2
  equatable: ^2.0.8
  preload_page_view: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  very_good_analysis: ^10.2.0

flutter:

  uses-material-design: true
  generate: true
  assets:
    - assets/databases/
    - assets/fonts/
    - assets/pageFonts/

  fonts:
    - family: KFGQPC
      fonts:
        - asset: assets/fonts/KFGQPC_mastaleeq.ttf
    - family: Juz name
      fonts:
        - asset: assets/fonts/juz_name.ttf
    - family: Surah name v2
      fonts:
        - asset: assets/fonts/surah_name_v4.ttf
    - family: Surah name v4
      fonts:
        - asset: assets/fonts/surah_name_v4.ttf